"""add seller to gem model

Revision ID: ee2bd9f7a7f1
Revises: 7db9ab4dcb28
Create Date: 2024-06-26 03:32:38.213216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # newly added by chidi


# revision identifiers, used by Alembic.
revision: str = 'ee2bd9f7a7f1'
down_revision: Union[str, None] = '7db9ab4dcb28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'gem', 'user', ['seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gem', type_='foreignkey')
    # ### end Alembic commands ###
